
// Generated by Cadence Genus(TM) Synthesis Solution 17.24-s038_1
// Generated on: Apr 22 2023 22:49:57 EDT (Apr 23 2023 02:49:57 UTC)

// Verification Directory fv/controller 

module controller(ph1, ph2, reset, Instr, Funct, Rd, ALUFlags, FlagW,
     PCWrite, MemWrite, RegWrite, IRWrite, AdrSrc, RegSrc, ALUOp,
     ALUSrcA, ALUSrcB, ResultSrc, ImmSrc);
  input ph1, ph2, reset;
  input [31:25] Instr;
  input [0:0] Funct;
  input [2:0] Rd;
  input [1:0] ALUFlags, FlagW;
  output PCWrite, MemWrite, RegWrite, AdrSrc, ALUOp, ALUSrcA, ImmSrc;
  output [3:0] IRWrite;
  output [1:0] RegSrc, ALUSrcB, ResultSrc;
  wire ph1, ph2, reset;
  wire [31:25] Instr;
  wire [0:0] Funct;
  wire [2:0] Rd;
  wire [1:0] ALUFlags, FlagW;
  wire PCWrite, MemWrite, RegWrite, AdrSrc, ALUOp, ALUSrcA, ImmSrc;
  wire [3:0] IRWrite;
  wire [1:0] RegSrc, ALUSrcB, ResultSrc;
  wire [0:0] cl_flagreg0_f_mid;
  wire [1:0] cl_Flags;
  wire [0:0] cl_flagreg1_f_mid;
  wire [3:0] dec_fsm_state;
  wire [0:0] cl_condreg_f_mid;
  wire [3:0] dec_fsm_statereg_f_mid;
  wire cl_CondExDelayed, n_0, n_2, n_3, n_4, n_5, n_8, n_10;
  wire n_11, n_12, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_20, n_23, n_24, n_25, n_26, n_27, n_28, n_29;
  wire n_32, n_33, n_34, n_36, n_38, n_39, n_40, n_41;
  wire n_42, n_43, n_44, n_46, n_48, n_49, n_50, n_51;
  wire n_52, n_53, n_54, n_55, n_56, n_57, n_58, n_59;
  wire n_60, n_62, n_63, n_64, n_65, n_67, n_68, n_70;
  wire n_71, n_73, n_74, n_75, n_76, n_77, n_79, n_80;
  wire n_82, n_83, n_84, n_87, n_91, n_92, n_93, n_96;
  wire n_117, n_118, n_119, n_124, n_128, n_129, n_130, n_131;
  assign ImmSrc = Instr[27];
  assign ALUSrcB[1] = ALUSrcA;
  nand3_1x g1770__8780(.a (n_92), .b (n_67), .c (n_96), .y (PCWrite));
  nand3_1x g1772__4296(.a (RegWrite), .b (Rd[0]), .c (n_2), .y (n_96));
  latch_c_1x \cl_flagreg0_f_slave_q_reg[0] (.ph (ph1), .d
       (cl_flagreg0_f_mid), .q (cl_Flags[0]));
  nor2_2x g1776__3772(.a (n_93), .b (n_17), .y (RegWrite));
  latch_c_1x \cl_flagreg1_f_slave_q_reg[0] (.ph (ph1), .d
       (cl_flagreg1_f_mid), .q (cl_Flags[1]));
  latch_c_1x \cl_flagreg0_f_master_q_reg[0] (.ph (ph2), .d (n_129), .q
       (cl_flagreg0_f_mid));
  nor2_2x g1780__1474(.a (n_33), .b (n_91), .y (MemWrite));
  nand3_1x g1779__4547(.a (dec_fsm_state[1]), .b (cl_CondExDelayed), .c
       (dec_fsm_state[0]), .y (n_93));
  latch_c_1x \cl_flagreg1_f_master_q_reg[0] (.ph (ph2), .d (n_119), .q
       (cl_flagreg1_f_mid));
  nand2_1x g1781__9682(.a (cl_CondExDelayed), .b (n_56), .y (n_92));
  nand2_1x g1782__2683(.a (cl_CondExDelayed), .b (n_44), .y (n_91));
  latch_c_1x \cl_condreg_f_slave_q_reg[0] (.ph (ph1), .d
       (cl_condreg_f_mid), .q (cl_CondExDelayed));
  latch_c_1x \dec_fsm_statereg_f_slave_q_reg[3] (.ph (ph1), .d
       (dec_fsm_statereg_f_mid[3]), .q (dec_fsm_state[3]));
  latch_c_1x \dec_fsm_statereg_f_master_q_reg[3] (.ph (ph2), .d (n_79),
       .q (dec_fsm_statereg_f_mid[3]));
  latch_c_1x \dec_fsm_statereg_f_slave_q_reg[1] (.ph (ph1), .d
       (dec_fsm_statereg_f_mid[1]), .q (dec_fsm_state[1]));
  latch_c_1x \cl_condreg_f_master_q_reg[0] (.ph (ph2), .d (n_82), .q
       (cl_condreg_f_mid));
  and2_1x g1789__7118(.a (n_83), .b (n_80), .y (n_87));
  a2o1_1x g1790__8757(.a (n_131), .b (FlagW[1]), .c (reset), .y (n_84));
  latch_c_1x \dec_fsm_statereg_f_slave_q_reg[2] (.ph (ph1), .d
       (dec_fsm_statereg_f_mid[2]), .q (dec_fsm_state[2]));
  latch_c_1x \dec_fsm_statereg_f_master_q_reg[1] (.ph (ph2), .d (n_77),
       .q (dec_fsm_statereg_f_mid[1]));
  and2_1x g1794__1786(.a (n_83), .b (n_131), .y (n_82));
  nand2_1x g1795__5953(.a (FlagW[0]), .b (n_131), .y (n_80));
  a2o1_1x g1799__5703(.a (n_76), .b (n_41), .c (n_73), .y (n_79));
  latch_c_1x \dec_fsm_statereg_f_master_q_reg[0] (.ph (ph2), .d (n_75),
       .q (dec_fsm_statereg_f_mid[0]));
  latch_c_1x \dec_fsm_statereg_f_master_q_reg[2] (.ph (ph2), .d (n_74),
       .q (dec_fsm_statereg_f_mid[2]));
  a2o1_1x g1809__7114(.a (n_46), .b (n_10), .c (n_68), .y (ALUSrcB[0]));
  nand3_1x g1798__5266(.a (n_71), .b (n_50), .c (n_65), .y (n_77));
  a2o1_1x g1806__6083(.a (n_64), .b (n_20), .c (n_63), .y (n_76));
  a2o1_1x g1803__2703(.a (n_60), .b (n_83), .c (n_58), .y (n_75));
  a2o1_1x g1804__5795(.a (n_42), .b (n_70), .c (n_62), .y (n_74));
  and2_1x g1805__7344(.a (n_83), .b (ALUOp), .y (n_73));
  nand3_1x g1807__1840(.a (n_70), .b (Funct), .c (n_10), .y (n_71));
  nand3_1x g1820__5019(.a (n_57), .b (n_67), .c (n_59), .y (n_68));
  nand2_1x g1808__9906(.a (n_53), .b (n_64), .y (n_65));
  nor2_1x g1812__8780(.a (Funct), .b (n_55), .y (n_63));
  and2_1x g1815__4296(.a (n_39), .b (n_64), .y (n_62));
  a2o1_1x g1819__3772(.a (n_38), .b (n_43), .c (n_34), .y (AdrSrc));
  nand2_1x g1811__1474(.a (n_59), .b (n_29), .y (n_60));
  nor2_1x g1814__4547(.a (n_27), .b (n_32), .y (n_58));
  inv_2x g1833(.a (n_56), .y (n_57));
  inv_1x g1823(.a (n_55), .y (n_70));
  inv_2x g1816(.a (n_54), .y (ALUOp));
  nand3_1x g1821__9682(.a (n_49), .b (n_28), .c (n_48), .y (n_54));
  nand2_1x g1813__2683(.a (n_10), .b (n_25), .y (n_53));
  a2o1_1x g1817__1309(.a (n_16), .b (cl_Flags[0]), .c (n_19), .y
       (n_52));
  nand2_1x g1818__6877(.a (n_3), .b (n_24), .y (n_51));
  nand3_1x g1810__2900(.a (n_49), .b (n_83), .c (n_48), .y (n_50));
  and2_1x g1840__2391(.a (n_46), .b (n_40), .y (IRWrite[3]));
  and2_1x g1829__7675(.a (n_46), .b (n_44), .y (IRWrite[1]));
  a2o1_1x g1822__7118(.a (n_43), .b (n_10), .c (n_36), .y (ALUSrcA));
  a2o1_1x g1828__8757(.a (n_41), .b (Funct), .c (n_40), .y (n_42));
  a2o1_1x g1827__1786(.a (dec_fsm_state[2]), .b (n_12), .c (n_38), .y
       (n_39));
  a2o1_1x g1836__5953(.a (n_41), .b (n_23), .c (n_36), .y
       (ResultSrc[1]));
  and2_1x g1830__5703(.a (n_46), .b (n_38), .y (ResultSrc[0]));
  nor2_1x g1834__7114(.a (n_33), .b (n_14), .y (n_34));
  nand2_1x g1831__5266(.a (n_83), .b (n_46), .y (n_55));
  nor2_2x g1841__2250(.a (n_33), .b (n_26), .y (n_56));
  inv_1x g1824(.a (n_32), .y (n_64));
  and2_1x g1826__6083(.a (n_43), .b (n_40), .y (IRWrite[2]));
  and2_1x g1825__2703(.a (n_43), .b (n_44), .y (IRWrite[0]));
  nand3_1x g1838__5795(.a (n_44), .b (dec_fsm_state[0]), .c (n_28), .y
       (n_29));
  nand2_1x g1832__7344(.a (n_83), .b (n_43), .y (n_32));
  nor3_1x g1837__1840(.a (n_26), .b (Instr[26]), .c (n_5), .y (n_27));
  nand3_1x g1835__5019(.a (n_124), .b (Instr[25]), .c (n_11), .y
       (n_25));
  mux2_c_1x g1839__1857(.d0 (cl_Flags[0]), .d1 (cl_Flags[1]), .s
       (n_18), .y (n_24));
  nor2_2x g1865__9906(.a (n_48), .b (n_10), .y (n_38));
  nand2_2x g1843__8780(.a (n_23), .b (n_40), .y (n_59));
  mux2_c_1x g1842__4296(.d0 (dec_fsm_state[1]), .d1 (n_10), .s
       (dec_fsm_state[0]), .y (n_49));
  nand2_2x g1844__3772(.a (n_23), .b (dec_fsm_state[3]), .y (n_33));
  nor2_2x g1845__1474(.a (n_23), .b (n_28), .y (n_46));
  inv_4x g1850(.a (n_20), .y (RegSrc[1]));
  inv_2x g1852(.a (n_26), .y (n_41));
  nor2_2x g1849__4547(.a (dec_fsm_state[0]), .b (dec_fsm_state[3]), .y
       (n_43));
  and2_1x g1847__9682(.a (cl_Flags[1]), .b (n_18), .y (n_19));
  a2o1_1x g1846__2683(.a (n_124), .b (dec_fsm_state[3]), .c (n_36), .y
       (n_17));
  mux2_c_1x g1848__1309(.d0 (Instr[29]), .d1 (n_15), .s (Instr[31]), .y
       (n_16));
  inv_4x g1861(.a (n_14), .y (n_44));
  nand2_2x g1855__6877(.a (Instr[26]), .b (n_8), .y (n_20));
  inv_2x g1860(.a (n_36), .y (n_67));
  nand2_2x g1858__2900(.a (n_10), .b (dec_fsm_state[2]), .y (n_26));
  nor2_2x g1857__2391(.a (n_10), .b (n_124), .y (n_40));
  inv_4x g1853(.a (dec_fsm_state[0]), .y (n_23));
  inv_1x g1851(.a (n_11), .y (n_12));
  nor2_2x g1854__7675(.a (Instr[26]), .b (n_8), .y (RegSrc[0]));
  nand2_2x g1868__7118(.a (n_48), .b (n_10), .y (n_14));
  nor2_1x g1862__8757(.a (Instr[25]), .b (Instr[27]), .y (n_5));
  inv_2x g1872(.a (n_4), .y (n_28));
  nor2_2x g1867__1786(.a (dec_fsm_state[3]), .b (n_124), .y (n_36));
  latch_c_1x \dec_fsm_statereg_f_slave_q_reg[0] (.ph (ph1), .d
       (dec_fsm_statereg_f_mid[0]), .q (dec_fsm_state[0]));
  nand2_1x g1863__5953(.a (Instr[31]), .b (cl_Flags[1]), .y (n_3));
  and2_1x g1864__5703(.a (Rd[2]), .b (Rd[1]), .y (n_2));
  nor2_1x g1866__7114(.a (Instr[29]), .b (Instr[31]), .y (n_18));
  nor2_1x g1856__5266(.a (Instr[26]), .b (Instr[27]), .y (n_11));
  inv_4x g1882(.a (Instr[27]), .y (n_8));
  inv_4x g1880(.a (dec_fsm_state[1]), .y (n_10));
  inv_1x g1874(.a (reset), .y (n_83));
  inv_1x g1869(.a (ALUFlags[0]), .y (n_0));
  inv_1x g1870(.a (cl_Flags[1]), .y (n_15));
  inv_2x g1873(.a (dec_fsm_state[3]), .y (n_4));
  inv_1x g4(.a (n_118), .y (n_119));
  mux2_c_1x g2(.d0 (n_15), .d1 (n_117), .s (n_84), .y (n_118));
  nand2_2x g3(.a (ALUFlags[1]), .b (n_83), .y (n_117));
  inv_2x drc_bufs1899(.a (n_48), .y (n_124));
  inv_2x drc_bufs1900(.a (dec_fsm_state[2]), .y (n_48));
  mux2_c_1x g1903(.d0 (n_128), .d1 (cl_Flags[0]), .s (n_87), .y
       (n_129));
  nor2_2x g1904(.a (n_0), .b (reset), .y (n_128));
  or2_1x g1905(.a (n_130), .b (Instr[30]), .y (n_131));
  mux2_c_1x g1906(.d0 (n_52), .d1 (n_51), .s (Instr[28]), .y (n_130));
endmodule

