set_db port:controller/ph1 .original_name {ph1}
set_db port:controller/ph2 .original_name {ph2}
set_db port:controller/reset .original_name {reset}
set_db {port:controller/Instr[31]} .original_name {Instr[31]}
set_db {port:controller/Instr[30]} .original_name {Instr[30]}
set_db {port:controller/Instr[29]} .original_name {Instr[29]}
set_db {port:controller/Instr[28]} .original_name {Instr[28]}
set_db {port:controller/Instr[27]} .original_name {Instr[27]}
set_db {port:controller/Instr[26]} .original_name {Instr[26]}
set_db {port:controller/Instr[25]} .original_name {Instr[25]}
set_db {port:controller/Funct[0]} .original_name {Funct[0]}
set_db {port:controller/Rd[2]} .original_name {Rd[2]}
set_db {port:controller/Rd[1]} .original_name {Rd[1]}
set_db {port:controller/Rd[0]} .original_name {Rd[0]}
set_db {port:controller/ALUFlags[1]} .original_name {ALUFlags[1]}
set_db {port:controller/ALUFlags[0]} .original_name {ALUFlags[0]}
set_db {port:controller/FlagW[1]} .original_name {FlagW[1]}
set_db {port:controller/FlagW[0]} .original_name {FlagW[0]}
set_db port:controller/PCWrite .original_name {PCWrite}
set_db port:controller/MemWrite .original_name {MemWrite}
set_db port:controller/RegWrite .original_name {RegWrite}
set_db {port:controller/IRWrite[3]} .original_name {IRWrite[3]}
set_db {port:controller/IRWrite[2]} .original_name {IRWrite[2]}
set_db {port:controller/IRWrite[1]} .original_name {IRWrite[1]}
set_db {port:controller/IRWrite[0]} .original_name {IRWrite[0]}
set_db port:controller/AdrSrc .original_name {AdrSrc}
set_db {port:controller/RegSrc[1]} .original_name {RegSrc[1]}
set_db {port:controller/RegSrc[0]} .original_name {RegSrc[0]}
set_db port:controller/ALUOp .original_name {ALUOp}
set_db port:controller/ALUSrcA .original_name {ALUSrcA}
set_db {port:controller/ALUSrcB[1]} .original_name {ALUSrcB[1]}
set_db {port:controller/ALUSrcB[0]} .original_name {ALUSrcB[0]}
set_db {port:controller/ResultSrc[1]} .original_name {ResultSrc[1]}
set_db {port:controller/ResultSrc[0]} .original_name {ResultSrc[0]}
set_db port:controller/ImmSrc .original_name {ImmSrc}



set_db {pin:controller/cl_flagreg0_f_slave_q_reg[0]/q} .original_name {cl/flagreg0/f/slave/q[0]/q}
set_db {pin:controller/cl_flagreg1_f_slave_q_reg[0]/q} .original_name {cl/flagreg1/f/slave/q[0]/q}
set_db {pin:controller/cl_flagreg0_f_master_q_reg[0]/q} .original_name {cl/flagreg0/f/master/q[0]/q}
set_db {pin:controller/cl_flagreg1_f_master_q_reg[0]/q} .original_name {cl/flagreg1/f/master/q[0]/q}
set_db {pin:controller/cl_condreg_f_slave_q_reg[0]/q} .original_name {cl/condreg/f/slave/q[0]/q}
set_db {pin:controller/dec_fsm_statereg_f_slave_q_reg[3]/q} .original_name {dec/fsm/statereg/f/slave/q[3]/q}
set_db {pin:controller/dec_fsm_statereg_f_master_q_reg[3]/q} .original_name {dec/fsm/statereg/f/master/q[3]/q}
set_db {pin:controller/dec_fsm_statereg_f_slave_q_reg[1]/q} .original_name {dec/fsm/statereg/f/slave/q[1]/q}
set_db {pin:controller/cl_condreg_f_master_q_reg[0]/q} .original_name {cl/condreg/f/master/q[0]/q}
set_db {pin:controller/dec_fsm_statereg_f_slave_q_reg[2]/q} .original_name {dec/fsm/statereg/f/slave/q[2]/q}
set_db {pin:controller/dec_fsm_statereg_f_master_q_reg[1]/q} .original_name {dec/fsm/statereg/f/master/q[1]/q}
set_db {pin:controller/dec_fsm_statereg_f_master_q_reg[0]/q} .original_name {dec/fsm/statereg/f/master/q[0]/q}
set_db {pin:controller/dec_fsm_statereg_f_master_q_reg[2]/q} .original_name {dec/fsm/statereg/f/master/q[2]/q}
set_db {pin:controller/dec_fsm_statereg_f_slave_q_reg[0]/q} .original_name {dec/fsm/statereg/f/slave/q[0]/q}
